version: '3.8'

services:
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
        container_name: elasticsearch
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            # - node.name=es
            - cluster.name=es-docker-cluster
            - MAX_LOCKED_MEMORY=unlimited
            - xpack.security.enabled=false
            - discovery.type=single-node
        volumes:
            - ./es_data_volume:/usr/share/elasticsearch/data
            - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
        networks:
            - demonet
        ports:
            - 9200:9200
            - 9300:9300
            
    api:
        build: .
        container_name: "demo-api"
        environment:
          - PYTHONPATH=/code/app
        volumes:
            - ./:/code
        ports:
            - 8000:80
        networks:
            - demonet
        depends_on:
            - "es"

networks:
    demonet:
